## Deliverable 2. Create a Customer Travel Destinations Map.

In [11]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [12]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("Weather_Database/WeatherPy_database.csv")
city_data_df.head()

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Ushuaia,AR,-54.8000,-68.3000,47.86,66,40,24.16,light rain
1,1,Rikitea,PF,-23.1203,-134.9692,77.41,80,46,10.40,light rain
2,2,Saint George,US,37.1041,-113.5841,59.47,42,1,1.99,clear sky
3,3,Tambura,SS,5.6000,27.4667,77.97,33,95,4.12,overcast clouds
4,4,Torbay,CA,47.6666,-52.7314,40.57,82,75,24.16,broken clouds

In [13]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 

min_temp = float(input("What is the minimum temperature (°F) you would like for your trip? "))
max_temp = float(input("What is the maximum temperature (°F) you would like for your trip? "))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 85

In [14]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
1,1,Rikitea,PF,-23.1203,-134.9692,77.41,80,46,10.40,light rain
3,3,Tambura,SS,5.6000,27.4667,77.97,33,95,4.12,overcast clouds
12,12,Kapaa,US,22.0752,-159.3190,80.92,77,40,4.00,scattered clouds
17,17,Ixtapa,MX,20.7000,-105.2000,81.63,69,1,11.50,clear sky
18,18,Avarua,CK,-21.2078,-159.7750,82.45,78,75,18.41,moderate rain
21,21,Sinnamary,GF,5.3833,-52.9500,78.19,88,100,11.07,light rain
22,22,Hilo,US,19.7297,-155.0900,78.53,42,75,6.91,light rain
24,24,Butaritari,KI,3.0707,172.7902,81.18,75,100,17.00,overcast clouds
25,25,Beira,MZ,-19.8436,34.8389,80.69,83,20,8.05,few clouds
28,28,Cockburn Town,TC,21.4612,-71.1419,80.56,69,40,11.50,scattered clouds

In [15]:
# 4a. Determine if there are any empty rows.
preferred_cities_df.count()

City_ID                165
City                   165
Country                165
Lat                    165
Lng                    165
Max Temp               165
Humidity               165
Cloudiness             165
Wind Speed             165
Current Description    165
dtype: int64

In [16]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
clean_df = preferred_cities_df.dropna()
clean_df

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
1,1,Rikitea,PF,-23.1203,-134.9692,77.41,80,46,10.40,light rain
3,3,Tambura,SS,5.6000,27.4667,77.97,33,95,4.12,overcast clouds
12,12,Kapaa,US,22.0752,-159.3190,80.92,77,40,4.00,scattered clouds
17,17,Ixtapa,MX,20.7000,-105.2000,81.63,69,1,11.50,clear sky
18,18,Avarua,CK,-21.2078,-159.7750,82.45,78,75,18.41,moderate rain
...,...,...,...,...,...,...,...,...,...,...
648,648,Cayenne,GF,4.9333,-52.3333,80.10,86,20,5.01,few clouds
649,649,Manaure,CO,11.7751,-72.4445,82.51,72,61,13.71,broken clouds
651,651,Belmonte,BR,-15.8631,-38.8828,79.30,82,100,6.82,light rain
655,655,Santa Rosa,PH,14.3122,121.1114,77.11,76,46,16.06,scattered clouds
660,660,Sao Jose Da Coroa Grande,BR,-8.8978,-35.1478,79.61,77,69,8.75,broken clouds

In [17]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = clean_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
1,Rikitea,PF,77.41,light rain,-23.1203,-134.9692,
3,Tambura,SS,77.97,overcast clouds,5.6000,27.4667,
12,Kapaa,US,80.92,scattered clouds,22.0752,-159.3190,
17,Ixtapa,MX,81.63,clear sky,20.7000,-105.2000,
18,Avarua,CK,82.45,moderate rain,-21.2078,-159.7750,
21,Sinnamary,GF,78.19,light rain,5.3833,-52.9500,
22,Hilo,US,78.53,light rain,19.7297,-155.0900,
24,Butaritari,KI,81.18,overcast clouds,3.0707,172.7902,
25,Beira,MZ,80.69,few clouds,-19.8436,34.8389,
28,Cockburn Town,TC,80.56,scattered clouds,21.4612,-71.1419,

In [18]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame.
for index, row in hotel_df.iterrows():
    
    # 6c. Get latitude and longitude from DataFrame
    lat = row["Lat"]
    lng = row["Lng"]
    params["location"] = f"{lat},{lng}"
    
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"    

    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url, params=params).json()   
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [19]:
# 7. Drop the rows where there is no Hotel Name.
clean_hotel_df = hotel_df.dropna()
clean_hotel_df

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
1,Rikitea,PF,77.41,light rain,-23.1203,-134.9692,People ThankYou
3,Tambura,SS,77.97,overcast clouds,5.6000,27.4667,Rikito Lodge
12,Kapaa,US,80.92,scattered clouds,22.0752,-159.3190,Sheraton Kauai Coconut Beach Resort
17,Ixtapa,MX,81.63,clear sky,20.7000,-105.2000,Hotel Plaza Providencia
18,Avarua,CK,82.45,moderate rain,-21.2078,-159.7750,Paradise Inn
...,...,...,...,...,...,...,...
648,Cayenne,GF,80.10,few clouds,4.9333,-52.3333,Hôtel Le Dronmi
649,Manaure,CO,82.51,broken clouds,11.7751,-72.4445,Hotel Palaaima
651,Belmonte,BR,79.30,light rain,-15.8631,-38.8828,Pousada Monte Carmelo O Pão
655,Santa Rosa,PH,77.11,scattered clouds,14.3122,121.1114,Erlyn’s Sta Rosa City Home
660,Sao Jose Da Coroa Grande,BR,79.61,broken clouds,-8.8978,-35.1478,Crôa Mares Hotel

In [20]:
# 8a. Create the output File (CSV)
output_data_file = "Vaction_Search/WeatherPy_vacation.csv"
# 8b. Export the City_Data into a csv
clean_hotel_df.to_csv(output_data_file, index_label="City_ID")

In [26]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description} and {Max Temp} °F</dd>
</dl>
"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = clean_hotel_df[["Lat", "Lng"]]

In [27]:
# 11a. Add a marker layer for each city to the map. 

fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)

# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))